name: Build Julius
on: 
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux x64
            os: ubuntu-20.04
            cache-key: linux-x64
            SDL_VERSION: 2.26.4
            SDL_MIXER_VERSION: 2.6.2
            BUILD_TARGET: linux
            DEPLOY: linux
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      SDL_VERSION: ${{ matrix.SDL_VERSION }}
      SDL_MIXER_VERSION: ${{ matrix.SDL_MIXER_VERSION }}
      BUILD_TARGET: ${{ matrix.BUILD_TARGET }}
      DEPLOY: ${{ matrix.DEPLOY }}
      SKIP_UPLOAD: ${{ matrix.SKIP_UPLOAD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache dependencies
        uses: actions/cache@v3
        if: ${{ matrix.cache-key }}
        with:
          path: deps
          key: ${{ matrix.cache-key }}-${{ env.SDL_VERSION }}-${{ env.SDL_MIXER_VERSION }}
      - name: Set up environment
        env:
          FILE_ENCRYPTION_IV: ${{ secrets.FILE_ENCRYPTION_IV }}
          FILE_ENCRYPTION_KEY: ${{ secrets.FILE_ENCRYPTION_KEY }}
        run: |
          ./.ci_scripts/setup_environment.sh
          ./.ci_scripts/install_dependencies.sh
      - name: Build and test
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
        run: |
          ./.ci_scripts/run_cmake.sh
          ./.ci_scripts/run_build.sh
      - name: all files
        run: |
          find .
      - name: Upload development artifacts
        env:
          UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        run: |
          ./.ci_scripts/build_upload.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: deploy/
